# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 532532df1cc2f7fe0cab1553afb2f2aa9bf38fc412755b4eb7f73d95ce0887eeaf215dc39ebe4eb9341a8ad555ee9dc1b5f3362c0f6a8f16034ae96a0c1431f2

test:
  secret_key_base: 3ec451d01cab01f101f11759b683c485d9e49bee5a661a2a200240e035e89d4d42d01c5655ab777d3f03dfc0737171af94e6a4d865060237e86b82a8135ca75f

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
